openapi: 3.0.3
info:
  title: Banner Management API
  description: Endpoints for managing homepage and about banners, including file uploads.
  version: 1.0.0

paths:
  /banners:
    get:
        summary: Get banner management data
        tags:
          - Banner Management
        security:
          - bearerAuth: []
        responses:
          '200':
            description: Banner management retrieved successfully
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/BannerManagementResponse'
          '500':
            description: Server error
            content:
              application/json:
                schema:
                  $ref: './main.yaml#/components/schemas/Error'
    put:
        summary: Update banner management data
        tags:
          - Banner Management
        security:
          - bearerAuth: []
        requestBody:
          required: true
          content:
            multipart/form-data:
              schema:
                $ref: '#/components/schemas/BannerManagementInput'
        responses:
          '200':
            description: Banner management updated successfully
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/BannerManagementResponse'
          '400':
            description: Validation error
            content:
              application/json:
                schema:
                  $ref: './main.yaml#/components/schemas/Error'
          '500':
            description: Server error
            content:
              application/json:
                schema:
                  $ref: './main.yaml#/components/schemas/Error'

components:
  schemas:
    BannerManagementInput:
      type: object
      properties:
        homepage:
          type: object
          properties:
            bannerOne:
              type: object
              properties:
                title: { type: string }
                highlightedText: { type: string }
                image1: { type: string, format: binary }
                subHead1: { type: string }
                subDescription1: { type: string }
                image2: { type: string, format: binary }
                subHead2: { type: string }
                subDescription2: { type: string }
                image3: { type: string, format: binary }
                subHead3: { type: string }
                subDescription3: { type: string }
            bannerTwo:
              type: object
              properties:
                backgroundImage: { type: string, format: binary }
                title: { type: string }
                description: { type: string }
                features:
                  type: array
                  items:
                    type: object
                    properties:
                      icon: { type: string }
                      title: { type: string }
                buttonName: { type: string }
                buttonUrl: { type: string }
        aboutBanner:
          type: object
          properties:
            submenu1:
              type: object
              properties:
                backgroundImage: { type: string, format: binary }
                title: { type: string }
                description: { type: string }
                images:
                  type: array
                  items: { type: string, format: binary }
            submenu2:
              type: object
              properties:
                backgroundImage: { type: string, format: binary }
                title: { type: string }
                description: { type: string }
                images:
                  type: array
                  items: { type: string, format: binary }
            submenu3:
              type: object
              properties:
                title: { type: string }
                description: { type: string }
            smallBoxes:
              type: array
              items:
                type: object
                properties:
                  count: { type: string }
                  label: { type: string }
                  description: { type: string }
    BannerManagementResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        data:
          $ref: '#/components/schemas/BannerManagementInput'
        message:
          type: string
          example: Banner management retrieved successfully
